[package]
name = "belief_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minvect = "0.1.1"

glow = "0.11.0"
glutin = "0.28"
winit = "0.26.1"
glow_mesh = "0.1.1"
ordered-float = "4.1.1"
